language:
  - js
compiler:
  - clang
install:
  - nvm install 10.6.0
  - npm install sha
before_script:
  - git fetch --unshallow
script:
  - make minigrace
  - make test || ( cat js/tests/test.js.log ; exit 1 )
  - (make minigrace.env && make module.test) || ( cat modules/tests/test.log ; exit 1 )
  - make VERBOSE="--verbose" self.test
sudo: false
